### PR TITLE
Added dependencies on lua and tcl for Lmod

### PR DESCRIPTION
**Pull request by bedroge**
There was an implicit dependency on Lua already (through luaposix/luafilesystem), but made it explicit in the Lmod ebuild. Also added a dependency on Tcl, since that was completely missing. Also see https://github.com/EESSI/compatibility-layer/issues/22.

### CODE REVIEW

**Review by peterstol — COMMENTED** [review]
Unsure about adding the tcl and lua dependancies as they are also provided by luaposix and luafilesystem.

**Comment by bedroge** [comment]
True for lua (though I thought it may be better to make it explicit, but maybe that doesn't really matter), but I don't see tcl anywhere?

**Comment by boegel** [comment]
@peterstol I don't see a problem in adding a direct dependency on Lua, since Lmod indeed requires Lua...

Tcl is definitely not pulled in automatically via luaposix or luafilesystem, but is required by Lmod if you want it to support reading Tcl module files (which we do).

**Comment by bedroge** [comment]
So, can we merge this? :-)

**Pull request merged**
