### PR TITLE
Build Archspec only for Python 3

### PR DESCRIPTION
**Pull request by bedroge**
The Python 2.7 wouldn't build anymore, because one of its dependencies (`click`) did not seem to have a Python 2 version anymore. Since we only need Archspec for Python 3 anyway, I've removed Python 2.7 support from its ebuild.

### CODE REVIEW

**Comment by boegel** [comment]
That's a bit strange, since the latest version of Click is supposed to be still compatible with Python 2.7 (see https://pypi.org/project/click/7.1.2/).

I'm fine with this change though, we only need `archspec` with Python 3 (for the init script and EasyBuild), we don't plan to use Python 2 for anything...

Maybe we should even flat out remove Python 2 from the compat layer?

**Comment by bedroge** [comment]
Yeah, it's a little bit strange, indeed. I guess they're slowly removing Python 2 support from ebuild files whenever possible (see https://gentoo.org/support/news-items/2020-02-07-python-2-7-eol.html). This is where the current ebuild files for click are:
https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-python/click

While the cached version of the ebuild for 7.1.2 in our 2020.08 pilot still has:
```
PYTHON_COMPAT=( python{2_7,3_{6,7,8,9}} pypy3 )
```

So it was recently removed, apparently.

I'm not sure if there is still (a lot of) stuff that depends on 2,7, and can't even find "Python-2.7" in any of the stage*.log files, so I'm not even sure where the installation comes from.
When I was debugging the archspec issue yesterday, I did find this page:
https://www.reddit.com/r/Gentoo/comments/czrglr/how_to_get_rid_of_python_27/
Maybe that helps if we really want to get rid of it.

**Comment by boegel** [comment]
@bedroge Let's open a separate issue on making sure we *don't* have Python 2 in the compat layer anymore (since sooner or later that'll be a security issue), and then go ahead and merge this one?

**Comment by bedroge** [comment]
Done!
https://github.com/EESSI/compatibility-layer/issues/36

**Pull request merged**
