### PR TITLE
define 2023.06 set, incl. archspec 0.2.1

### PR DESCRIPTION
**Pull request by boegel**
Updating archspec to 0.2.1 would be very nice, since that adds support for AMD Genoa (a.k.a. `zen4`), cfr. https://github.com/archspec/archspec/releases/tag/v0.2.1

Both `six` and `click` are no longer required for archspec 0.2.1

WIP since more work is needed for archspec 0.2.1 (but I'm not very familiar with the correct procedure to add a new ebuild)

### CODE REVIEW

**Comment by boegel** [comment]
Next step is to actually test the installation of the new `archspec` ebuild...

**Review by trz42 — APPROVED** [review]
The compatibility layer 2023.06 builds with the suggested changes. Removing outdated ebuilds is ok. The changes to improve/fix failing `pkgcheck` GHA are reasonable. For possible improvements to that issue https://github.com/EESSI/gentoo-overlay/issues/94 was opened.

**Comment by boegel** [comment]
@trz42 Out of curiosity: were the old `archspec` ebuilds causing trouble with `pkgcheck`?

I do agree that's it's fine to remove them, we really want the latest `archspec`...

**Comment by trz42** [comment]
@boegel Yes they rauses some errors/warnings.

**Pull request merged**
