### PR TITLE
2020.11 sets

### PR DESCRIPTION
**Pull request by bedroge**
This adds a set for 2020.11. The only new package for now is `sys-libs/pam`, which we need for RStudio. Also it adds arch-specific sets, since `opa-psm2` only works on `x86_64`.

### CODE REVIEW

**Comment by bedroge** [comment]
Do we also want to bump `rdma-core` to 31.2?
See https://github.com/linux-rdma/rdma-core/releases

**Comment by boegel** [comment]
> Do we also want to bump `rdma-core` to 31.2?
> See https://github.com/linux-rdma/rdma-core/releases

Yes, it's a bugfix update, so I'd bump to that.

**Review by boegel — APPROVED** [review]

**Comment by boegel** [comment]
@bedroge We need an accompanying PR in `compatibility-layer` to pick up the arch-specific set files?

**Comment by bedroge** [comment]
Yep, still need to do that.

**Pull request merged**
