### PR TITLE
Add lmod 8.4.20 and deps from Science and Base layer

### PR DESCRIPTION
**Pull request by peterstol**
lmod ebuild from the Science layer + dependencies from the Gentoo Base, which use the improved Lua eclass.
Tested on Linux x86_64

### CODE REVIEW

**Comment by bedroge** [comment]
Hmm... that's quite a lot. Do we really need all those dependencies from the gentoo overlay (especially all the different lua versions and patches)? Maybe we should just include only lmod itself?

**Comment by peterstol** [comment]
> Hmm... that's quite a lot. Do we really need all those dependencies from the gentoo overlay (especially all the different lua versions and patches)? Maybe we should just include only lmod itself?

True, but figuring out what exactly is used is more work than including it. When lmod stabilizes in the gentoo base it is easy to remove and we do not have to force the eessi lua eclass. In the mean time we can clean out unused ebuilds from the eessi overlay and have a stable lmod to fall back on.

**Comment by bedroge** [comment]
But does lmod have dependencies from the science overlay? If not, then they should all be included in the Gentoo overlay already (and work well, except for the `luaposix` one)?

It's probably a matter of finding the right balance between including everything in our overlay and specifying the version numbers in our set files (so that everything is more or less fixed, though that's probably not entirely possible), and keeping our overlay small(er) and depending more on the Gentoo files (which may break things every now and then, but should be less work otherwise). Maybe we can add this to the agenda of tomorrow's meeting?

**Comment by peterstol** [comment]
replaced by PR #45

**Pull request closed without merging**
