### PR TITLE
sys-apps/archspec: Keyword ~riscv and dev-python/click version bump

### PR DESCRIPTION
**Pull request by wiredhikari**

### CODE REVIEW

**Review by bedroge — COMMENTED** [review]
I'm not really sure about the version bump of `click`. These `archspec` versions had very specific versions of `click` listed, see for instance:
https://github.com/archspec/archspec/blob/v0.1.3/pyproject.toml#L30

**Comment by wiredhikari** [comment]
We dont have older versions of [dev-python/click](https://github.com/gentoo/gentoo/tree/master/dev-python/click) in gentoo repository. So we wont be able to compile `sys-apps/archspec`

**Comment by ocaisa** [comment]
In version 0.1.4 they break down the required click version according to the Python version, I suspect that with the prefix python a later click version will work just fine

**Comment by ocaisa** [comment]
See https://github.com/archspec/archspec/blob/v0.1.4/pyproject.toml#L30-L35

**Review by bedroge — APPROVED** [review]

**Pull request merged**
