### PR TITLE
add arm64 to keywords in opa-psm2 ebuild

### PR DESCRIPTION
**Pull request by boegel**
fix for the following issue I hit on Arm64:

```
$ emerge @2020.10
 * IMPORTANT: 4 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.
Calculating dependencies... done!
!!! All ebuilds that could satisfy "sys-fabric/opa-psm2" have been masked.
!!! One of the following masked packages is required to complete your request:
- sys-fabric/opa-psm2-11.2.185::eessi (masked by: missing keyword)
- sys-fabric/opa-psm2-11.2.86::eessi (masked by: missing keyword)
(dependency required by "@2020.10" [argument])
For more information, see the MASKED PACKAGES section in the emerge
man page or refer to the Gentoo Handbook.
```

### CODE REVIEW

**Comment by boegel** [comment]
Hmm, hold on... The `ebuild` doesn't actually work on Arm64:

```
/cvmfs/pilot.eessi-hpc.org/2020.10/compat/aarch64/var/tmp/portage/sys-fabric/opa-psm2-11.2.185/work/opa-psm2-PSM2_11.2.185/buildflags.mak:127: *** recipe commences before first target.  Stop.
```

**Comment by boegel** [comment]
I manually removed `sys-fabric/opa-psm2` from `/cvmfs/pilot.eessi-hpc.org/2020.10/compat/aarch64/etc/portage/sets/2020.10` to make `emerge @2020.10` to work for `compat/aarch64`.

I don't have high hopes for fixing the build of `opa-psm2` on Arm64...

**Comment by bedroge** [comment]
This was solved in #30, so I think this PR can be closed?

**Comment by boegel** [comment]
Yep!

**Pull request closed without merging**
